/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-06-26 16:27:34 UTC)
 * on 2013-07-04 at 14:37:22 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.ratings;

/**
 * Service definition for Ratings (v1).
 *
 * <p>
 * Rating API for Mensa Furtwangen.
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link RatingsRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Ratings extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.15.0-rc of the  library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://mensa-furtwangen.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "ratings/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Ratings(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Ratings(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "fetchDeviceMenuRating".
   *
   * This request holds the parameters needed by the the ratings server.  After setting any optional
   * parameters, call the {@link FetchDeviceMenuRating#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.google.api.services.ratings.model.DeviceMenuRatingQuery}
   * @return the request
   */
  public FetchDeviceMenuRating fetchDeviceMenuRating(com.google.api.services.ratings.model.DeviceMenuRatingQuery content) throws java.io.IOException {
    FetchDeviceMenuRating result = new FetchDeviceMenuRating(content);
    initialize(result);
    return result;
  }

  public class FetchDeviceMenuRating extends RatingsRequest<com.google.api.services.ratings.model.Rating> {

    private static final String REST_PATH = "fetchDeviceMenuRating";

    /**
     * Create a request for the method "fetchDeviceMenuRating".
     *
     * This request holds the parameters needed by the the ratings server.  After setting any optional
     * parameters, call the {@link FetchDeviceMenuRating#execute()} method to invoke the remote
     * operation. <p> {@link FetchDeviceMenuRating#initialize(com.google.api.client.googleapis.service
     * s.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param content the {@link com.google.api.services.ratings.model.DeviceMenuRatingQuery}
     * @since 1.13
     */
    protected FetchDeviceMenuRating(com.google.api.services.ratings.model.DeviceMenuRatingQuery content) {
      super(Ratings.this, "POST", REST_PATH, content, com.google.api.services.ratings.model.Rating.class);
    }

    @Override
    public FetchDeviceMenuRating setAlt(java.lang.String alt) {
      return (FetchDeviceMenuRating) super.setAlt(alt);
    }

    @Override
    public FetchDeviceMenuRating setFields(java.lang.String fields) {
      return (FetchDeviceMenuRating) super.setFields(fields);
    }

    @Override
    public FetchDeviceMenuRating setKey(java.lang.String key) {
      return (FetchDeviceMenuRating) super.setKey(key);
    }

    @Override
    public FetchDeviceMenuRating setOauthToken(java.lang.String oauthToken) {
      return (FetchDeviceMenuRating) super.setOauthToken(oauthToken);
    }

    @Override
    public FetchDeviceMenuRating setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (FetchDeviceMenuRating) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public FetchDeviceMenuRating setQuotaUser(java.lang.String quotaUser) {
      return (FetchDeviceMenuRating) super.setQuotaUser(quotaUser);
    }

    @Override
    public FetchDeviceMenuRating setUserIp(java.lang.String userIp) {
      return (FetchDeviceMenuRating) super.setUserIp(userIp);
    }

    @Override
    public FetchDeviceMenuRating set(String parameterName, Object value) {
      return (FetchDeviceMenuRating) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "fetchTotalMenuRating".
   *
   * This request holds the parameters needed by the the ratings server.  After setting any optional
   * parameters, call the {@link FetchTotalMenuRating#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.google.api.services.ratings.model.TotalMenuRatingQuery}
   * @return the request
   */
  public FetchTotalMenuRating fetchTotalMenuRating(com.google.api.services.ratings.model.TotalMenuRatingQuery content) throws java.io.IOException {
    FetchTotalMenuRating result = new FetchTotalMenuRating(content);
    initialize(result);
    return result;
  }

  public class FetchTotalMenuRating extends RatingsRequest<com.google.api.services.ratings.model.Rating> {

    private static final String REST_PATH = "fetchTotalMenuRating";

    /**
     * Create a request for the method "fetchTotalMenuRating".
     *
     * This request holds the parameters needed by the the ratings server.  After setting any optional
     * parameters, call the {@link FetchTotalMenuRating#execute()} method to invoke the remote
     * operation. <p> {@link FetchTotalMenuRating#initialize(com.google.api.client.googleapis.services
     * .AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param content the {@link com.google.api.services.ratings.model.TotalMenuRatingQuery}
     * @since 1.13
     */
    protected FetchTotalMenuRating(com.google.api.services.ratings.model.TotalMenuRatingQuery content) {
      super(Ratings.this, "POST", REST_PATH, content, com.google.api.services.ratings.model.Rating.class);
    }

    @Override
    public FetchTotalMenuRating setAlt(java.lang.String alt) {
      return (FetchTotalMenuRating) super.setAlt(alt);
    }

    @Override
    public FetchTotalMenuRating setFields(java.lang.String fields) {
      return (FetchTotalMenuRating) super.setFields(fields);
    }

    @Override
    public FetchTotalMenuRating setKey(java.lang.String key) {
      return (FetchTotalMenuRating) super.setKey(key);
    }

    @Override
    public FetchTotalMenuRating setOauthToken(java.lang.String oauthToken) {
      return (FetchTotalMenuRating) super.setOauthToken(oauthToken);
    }

    @Override
    public FetchTotalMenuRating setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (FetchTotalMenuRating) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public FetchTotalMenuRating setQuotaUser(java.lang.String quotaUser) {
      return (FetchTotalMenuRating) super.setQuotaUser(quotaUser);
    }

    @Override
    public FetchTotalMenuRating setUserIp(java.lang.String userIp) {
      return (FetchTotalMenuRating) super.setUserIp(userIp);
    }

    @Override
    public FetchTotalMenuRating set(String parameterName, Object value) {
      return (FetchTotalMenuRating) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertRating".
   *
   * This request holds the parameters needed by the the ratings server.  After setting any optional
   * parameters, call the {@link InsertRating#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.google.api.services.ratings.model.Rating}
   * @return the request
   */
  public InsertRating insertRating(com.google.api.services.ratings.model.Rating content) throws java.io.IOException {
    InsertRating result = new InsertRating(content);
    initialize(result);
    return result;
  }

  public class InsertRating extends RatingsRequest<com.google.api.services.ratings.model.Rating> {

    private static final String REST_PATH = "rating";

    /**
     * Create a request for the method "insertRating".
     *
     * This request holds the parameters needed by the the ratings server.  After setting any optional
     * parameters, call the {@link InsertRating#execute()} method to invoke the remote operation. <p>
     * {@link
     * InsertRating#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.google.api.services.ratings.model.Rating}
     * @since 1.13
     */
    protected InsertRating(com.google.api.services.ratings.model.Rating content) {
      super(Ratings.this, "POST", REST_PATH, content, com.google.api.services.ratings.model.Rating.class);
    }

    @Override
    public InsertRating setAlt(java.lang.String alt) {
      return (InsertRating) super.setAlt(alt);
    }

    @Override
    public InsertRating setFields(java.lang.String fields) {
      return (InsertRating) super.setFields(fields);
    }

    @Override
    public InsertRating setKey(java.lang.String key) {
      return (InsertRating) super.setKey(key);
    }

    @Override
    public InsertRating setOauthToken(java.lang.String oauthToken) {
      return (InsertRating) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertRating setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertRating) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertRating setQuotaUser(java.lang.String quotaUser) {
      return (InsertRating) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertRating setUserIp(java.lang.String userIp) {
      return (InsertRating) super.setUserIp(userIp);
    }

    @Override
    public InsertRating set(String parameterName, Object value) {
      return (InsertRating) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeRating".
   *
   * This request holds the parameters needed by the the ratings server.  After setting any optional
   * parameters, call the {@link RemoveRating#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public RemoveRating removeRating(java.lang.Long id) throws java.io.IOException {
    RemoveRating result = new RemoveRating(id);
    initialize(result);
    return result;
  }

  public class RemoveRating extends RatingsRequest<com.google.api.services.ratings.model.Rating> {

    private static final String REST_PATH = "rating/{id}";

    /**
     * Create a request for the method "removeRating".
     *
     * This request holds the parameters needed by the the ratings server.  After setting any optional
     * parameters, call the {@link RemoveRating#execute()} method to invoke the remote operation. <p>
     * {@link
     * RemoveRating#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveRating(java.lang.Long id) {
      super(Ratings.this, "DELETE", REST_PATH, null, com.google.api.services.ratings.model.Rating.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveRating setAlt(java.lang.String alt) {
      return (RemoveRating) super.setAlt(alt);
    }

    @Override
    public RemoveRating setFields(java.lang.String fields) {
      return (RemoveRating) super.setFields(fields);
    }

    @Override
    public RemoveRating setKey(java.lang.String key) {
      return (RemoveRating) super.setKey(key);
    }

    @Override
    public RemoveRating setOauthToken(java.lang.String oauthToken) {
      return (RemoveRating) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveRating setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveRating) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveRating setQuotaUser(java.lang.String quotaUser) {
      return (RemoveRating) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveRating setUserIp(java.lang.String userIp) {
      return (RemoveRating) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveRating setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveRating set(String parameterName, Object value) {
      return (RemoveRating) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Ratings}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Ratings}. */
    @Override
    public Ratings build() {
      return new Ratings(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link RatingsRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setRatingsRequestInitializer(
        RatingsRequestInitializer ratingsRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(ratingsRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
