/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-04-01 18:14:47 UTC)
 * on 2014-04-14 at 13:18:43 UTC 
 * Modify at your own risk.
 */

package com.appspot.mensa_furtwangen.thumbs.model;

/**
 * Model definition for ThumbsResult.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the thumbs. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ThumbsResult extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String deviceState;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer thumbsDown;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer thumbsUp;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDeviceState() {
    return deviceState;
  }

  /**
   * @param deviceState deviceState or {@code null} for none
   */
  public ThumbsResult setDeviceState(java.lang.String deviceState) {
    this.deviceState = deviceState;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getThumbsDown() {
    return thumbsDown;
  }

  /**
   * @param thumbsDown thumbsDown or {@code null} for none
   */
  public ThumbsResult setThumbsDown(java.lang.Integer thumbsDown) {
    this.thumbsDown = thumbsDown;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getThumbsUp() {
    return thumbsUp;
  }

  /**
   * @param thumbsUp thumbsUp or {@code null} for none
   */
  public ThumbsResult setThumbsUp(java.lang.Integer thumbsUp) {
    this.thumbsUp = thumbsUp;
    return this;
  }

  @Override
  public ThumbsResult set(String fieldName, Object value) {
    return (ThumbsResult) super.set(fieldName, value);
  }

  @Override
  public ThumbsResult clone() {
    return (ThumbsResult) super.clone();
  }

}
